##Sale Prediction from Existing Customer
Logistic Regression

In [1]:
import pandas as pd
import numpy as np

Creating dataset

In [2]:
Age = [53,47,45.7,22,22.2,46,49,23.3,18.3,23.6,55,24,50,24,25,48,36,34,28,29,30,50,32,31,40,34,35,60,37,38, 57 ,43,31,24,31,41,28,50]
Salary = [55794,56957,39343,46205,37731,83088,81363,56642,60150,54445,64445,16969,12635,22391,45638,21872,14586,39343,46205,57081,61111,74523,67938,66029,93904,84521,91708,98273,65478,13812,55210,19431,12568,15582,16589,57189,63218,91738,]
Age = [int(i) for i in Age]

1. If age < mean age and salary < mean salary then status == 0
2. Else status == 1

In [3]:
Status = []
for i in zip(Age,Salary):
  if i[0] <= np.mean(Age) and i[1] <= np.mean(Salary):
    Status.append(0)
  else:
    Status.append(1)

In [4]:
len(Salary)

38

In [5]:
len(Age)

38

In [6]:
len(Status)

38

In [7]:
list_of_tuples = list(zip(Age, Salary, Status))

In [8]:

dataset= pd.DataFrame(list_of_tuples, columns = ['Age','Salary','Status'])

##Summaize Dataset

In [9]:
dataset.shape

(38, 3)

In [10]:
dataset.head(5) #top 5 values

Age  Salary  Status
0   53   55794       1
1   47   56957       1
2   45   39343       1
3   22   46205       0
4   22   37731       0

In [11]:
dataset.tail(5)

Age  Salary  Status
33   24   15582       0
34   31   16589       0
35   41   57189       1
36   28   63218       1
37   50   91738       1

##Segregate Dataset into X(input/independentVariable) & Y(Output/dependentVariable)

In [12]:
X = dataset.iloc[:, :-1].values
X

array([[   53, 55794],
       [   47, 56957],
       [   45, 39343],
       [   22, 46205],
       [   22, 37731],
       [   46, 83088],
       [   49, 81363],
       [   23, 56642],
       [   18, 60150],
       [   23, 54445],
       [   55, 64445],
       [   24, 16969],
       [   50, 12635],
       [   24, 22391],
       [   25, 45638],
       [   48, 21872],
       [   36, 14586],
       [   34, 39343],
       [   28, 46205],
       [   29, 57081],
       [   30, 61111],
       [   50, 74523],
       [   32, 67938],
       [   31, 66029],
       [   40, 93904],
       [   34, 84521],
       [   35, 91708],
       [   60, 98273],
       [   37, 65478],
       [   38, 13812],
       [   57, 55210],
       [   43, 19431],
       [   31, 12568],
       [   24, 15582],
       [   31, 16589],
       [   41, 57189],
       [   28, 63218],
       [   50, 91738]])

In [13]:
Y = dataset.iloc[:,-1].values
Y

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1])

## Splitting Datasett into Train & Test

In [14]:
!pip install scikit-learn


In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

##Feature Scadlling

we scale our data to make all the features contribute equality to the result

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
X_train

array([[ 0.55542597, -1.38176761],
       [-1.01631135, -1.53996457],
       [-0.43725023, -1.66384237],
       [ 1.13448709,  1.59010754],
       [ 0.38997994,  0.17011619],
       [ 1.71354821,  0.08877772],
       [-0.43725023, -1.49857607],
       [-1.51264945,  0.29181564],
       [-1.01631135, -1.26010926],
       [ 0.80359502,  1.23458567],
       [-0.18908118, -0.56336859],
       [-0.93358834, -0.30463909],
       [-1.09903437,  0.14763405],
       [ 0.05908787,  0.51080068],
       [ 0.88631804,  0.1605808 ],
       [ 1.13448709, -1.66108861],
       [ 1.96171726,  1.85870123],
       [ 0.30725692,  1.67913186],
       [ 1.05176407,  1.1636868 ],
       [-0.43725023,  0.53344721],
       [-1.18175739, -0.62962307],
       [-0.68541928, -0.28133494],
       [ 1.13448709,  0.88255736],
       [-0.60269627,  0.1656773 ],
       [-1.09903437,  0.05733561],
       [-0.68541928,  0.41791288],
       [-1.18175739, -0.28133494],
       [ 1.38265614,  0.11278058]])

##Training

In [18]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression() #loading the algo
model.fit(X_train,y_train ) #train

LogisticRegression()

##Prediction for all Test Data

In [20]:
y_pred = model.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score

print("Accuracy of the model: {0}%".format(accuracy_score(y_test, y_pred)*100))

Accuracy of the model: 90.0%


##Pridicting, wheather new custmer with Age & Salary will Buy or NOT

In [19]:
age = int(input("Enter New custmer's Age: "))
sal = int(input("Enter New custmer's Salary: "))

newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)

if result == 1:
  print('custmer will buy')
else:
  print('custmer will not buy')

Enter New custmer's Age: 55
Enter New custmer's Salary: 50000
[1]
custmer will buy
